name: Build Binaries

on:
  push:
    paths-ignore:
      - '.github/*'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '*.md'

jobs:
  build:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: microsoft/setup-msbuild@v2
      with:
        vs-prerelease: true
        msbuild-architecture: x64
    - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
      run: dotnet nuget locals all --clear
    - name: Build
      run: msbuild -property:Configuration=debug BuildAllTargets.proj
    - uses: actions/upload-artifact@v4
      with:
        name: Mile.Xaml_CI_Build
        path: Output\Binaries
